### ISSUE TITLE
A little problem with the inference code

### ISSUE THREAD

**Issue by 834799106** [CISiPLab/cisip-FIRe#5]
https://github.com/CISiPLab/cisip-FIRe/blob/554d54a4dba71adc87176c1ac0e12f3864bf825f/inference/web.py#L39
I want to ask what is the function of this ’code_string‘ . I initially got an error here, and it works fine when I set it to 'None'. 
In addition, when I have uploaded a picture, I will terminate the program and refresh the web page, and then re-run it is still the result of uploading the picture last time. Is it that I did not make a correct step?

**Comment by jiuntian** [comment]
Hi thanks for feedback. The function of code_string is to display the binary hash code of the query image, for example: `00110000`. 

Are running on 16 bit setting? My apologize, there are some mistake in code that was not realize during the development as I mostly testing it on 64 or 128 bit.

```
 ​    ​code_string​ ​=​ ​'​\n​'​.​join​(​code_string​[​i​:​i​ ​+​ ​32​] ​for​ ​i​ ​in​ ​range​(​0​, ​len​(​code_string​), ​32​))
```

In this line 40, it is to split the binary code into segments of 32. This works well then the number of bit is a multiply of 32, but could cause problem on code length that is less than 32 bit. Would you mind to try change 32 to 8 instead, and try again? 

Also, it would be great if you can also share to us on what exact error is thrown.

To infer an image, first is to get the inference backend up, then you can navigate to the webpage, and upload an image. The top k retrieved results will return when the retrieval is done. For similar image, we expect to get same results every time.


Regards.

**Comment by 834799106** [comment]
Thank you for your patient reply. The problem I have is mainly caused by importing the model trained in other modules (non-hashed). In addition, the second point mentioned above is because my browser does not automatically clear the cache. But I have achieved what I wanted to achieve. Thank you very much.
