### ISSUE TITLE
How to run dataset roxford5kdelgembed

### ISSUE THREAD

**Issue by tranduyanhvyvp** [CISiPLab/cisip-FIRe#8]
I already download the dataset from the repo and try to run it but not work. Can you show the tutorial ? thks !

**Comment by tranduyanhvyvp** [comment]
first when i run the dataset, i not use the backbone in arch_orthohash.py and i config in orthocos.yaml resnet50 and usedb as train but it said Dimension out of range (expected to be in range of [-1, 0], but got 1) so how can i fix this tks

**Comment by jiuntian** [comment]
To use `roxford5kdelgembed`, please use `linear` backbone, feel free to let us know if there're any other problems.

**Comment by tranduyanhvyvp** [comment]
> To use `roxford5kdelgembed`, please use `linear` backbone, feel free to let us know if there're any other problems.

But when i change it to linear it still have the same problem "cisip-FIRe/functions/loss/orthocos.py", line 47, in forward
    labels = labels.argmax(1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)"
So how to fix this thks!

**Comment by jiuntian** [comment]
Can you share the complete log file so that I can look into? In first few
line it should indicate where is the log directory, and the log file is
named log.txt in that directory.

**Comment by tranduyanhvyvp** [comment]
> can look into? I

INFO 18-09-22 19:58:36: Log directory: logs/orthocos_linear_orthohash_2048_roxford5kdelgembed_100_0.0001_adam/007_test_0
INFO 18-09-22 19:58:36: {
  "arch": "orthohash",
  "arch_kwargs": {
    "arch": "orthohash",
    "nbit": 2048,
    "nclass": 0,
    "pretrained": true,
    "freeze_weight": false,
    "bias": false,
    "backbone": "linear",
    "in_channels": null
  },
  "batch_size": 64,
  "max_batch_size": 256,
  "dataset": "roxford5kdelgembed",
  "device": "cuda:0",
  "dfolder": "",
  "multiclass": false,
  "dataset_kwargs": {
    "resize": 0,
    "crop": 0,
    "norm": 2,
    "evaluation_protocol": 1,
    "use_db_as_train": true,
    "train_ratio": 1,
    "reset": false,
    "separate_multiclass": false,
    "train_skip_preprocess": false,
    "db_skip_preprocess": false,
    "test_skip_preprocess": false,
    "dataset_name_suffix": "",
    "neighbour_topk": 5,
    "no_augmentation": false,
    "data_folder": "",
    "use_random_augmentation": false
  },
  "optim": "adam",
  "optim_kwargs": {
    "lr": 0.0001,
    "momentum": 0.9,
    "nesterov": false,
    "betas": [
      0.9,
      0.999
    ],
    "alpha": 0.99,
    "weight_decay": 0.0005
  },
  "epochs": 100,
  "scheduler": "step",
  "scheduler_kwargs": {
    "step_size": 80,
    "gamma": 0.1,
    "milestones": "0.5,0.75",
    "linear_init_lr": 0.001,
    "linear_last_lr": 1e-05
  },
  "save_interval": 0,
  "eval_interval": 10,
  "shuffle_database": false,
  "tag": "test",
  "seed": 0,
  "loss": "orthocos",
  "loss_param": {
    "ce": 1,
    "m": 0.3,
    "s": 8,
    "quan": 0,
    "quan_type": "cs",
    "multiclass_loss": "label_smoothing",
    "ce_fc_nclass": 0,
    "cossim_ce": true,
    "learn_cent": false,
    "sign_cent": true,
    "hash_fc_output": "bn",
    "cent_init": "M",
    "multiclass": false,
    "nbit": 2048,
    "device": "cuda:0"
  },
  "backbone_lr_scale": 0.1,
  "start_epoch_from": 0,
  "resume_dir": "",
  "save_checkpoint": false,
  "load_from": "",
  "save_model": false,
  "save_best_model_only": false,
  "discard_hash_outputs": false,
  "benchmark": false,
  "num_worker": -1,
  "wandb_enable": false,
  "disable_tqdm": false,
  "R": 0,
  "distance_func": "hamming",
  "zero_mean_eval": false,
  "logdir": "logs/orthocos_linear_orthohash_2048_roxford5kdelgembed_100_0.0001_adam/007_test_0"
}
INFO 18-09-22 19:58:36: Creating Datasets
INFO 18-09-22 19:58:36: Number of data in database.txt: 4993
INFO 18-09-22 19:58:36: Number of data in test.txt: 70
INFO 18-09-22 19:58:36: Number of data in database.txt: 4993
INFO 18-09-22 19:58:36: Creating Model
INFO 18-09-22 19:58:36: Using DataParallel Model. Device id = [0]. is_cpu=False device=cuda:0
INFO 18-09-22 19:58:37: DataParallelPassthrough(
  (module): ArchOrthoHash(
    (backbone): LinearBackbone()
    (ce_fc): CosSim(in_features=2048, n_class=0, learn_centroid=False)
    (hash_fc): Sequential(
      (0): Linear(in_features=2048, out_features=2048, bias=False)
      (1): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
)
INFO 18-09-22 19:58:37: Preprocessing done!
INFO 18-09-22 19:58:37: Total Bit: 2048
INFO 18-09-22 19:58:37: Training Start
INFO 18-09-22 19:58:37: Epoch [1/100] LR: 0.000100
 here is the log file

**Comment by tranduyanhvyvp** [comment]
Traceback (most recent call last):
  File "/home/saplab/hoangnnh/zzz/cisip-FIRe/train.py", line 400, in <module>
    train_general.main(config,
  File "/home/saplab/hoangnnh/zzz/cisip-FIRe/scripts/train_general.py", line 505, in main
    train_meters = train_hashing(optimizer, model, train_loader, device, loss_param['loss'],
  File "/home/saplab/hoangnnh/zzz/cisip-FIRe/scripts/train_general.py", line 168, in train_hashing
    output, loss = get_output_and_loss_general(method, model, criterion,
  File "/home/saplab/hoangnnh/zzz/cisip-FIRe/scripts/train_general.py", line 72, in get_output_and_loss_general
    return f(model, criterion, data, labels, index, onehot, loss_name, loss_cfg, stage, no_loss)
  File "/home/saplab/hoangnnh/zzz/cisip-FIRe/scripts/train_supervised.py", line 11, in get_output_and_loss_supervised
    loss = criterion(logits, code_logits, labels, onehot=onehot)
  File "/home/saplab/anaconda3/envs/thaiminhpv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saplab/hoangnnh/zzz/cisip-FIRe/functions/loss/orthocos.py", line 47, in forward
    labels = labels.argmax(1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by jiuntian** [comment]
Just realized that you are doing training on roxford5k, but that is not
possible at the moment. In orthohash we trained on gldv2 and then evaluate
on roxford5k dataset.

**Comment by tranduyanhvyvp** [comment]
> taset.

oh now i understand so how can i evaluate roxford5k after trained it on gldv2
